# This function takes a bed file generated by [bedtools bamtobed] as one input (has information about the 5' end of each distinct mappable read), and another bed file as another input.
# This version only works well for reads generate from single end sequencing
reads_overlap_peaks <- function(reads_bed_file, peaks_bed_file, strand){
  #[reads_bed_file] is the name of the bed file generated by bedtools bamtobed, which has the information about the 5' position of each read
  #[peaks_bed_file] is the name of the bed file that has coordinates of regions enriched for 5hmc reads
  #[strand] could be "plus", "minus". It informs which strand of reads will be compared to the peaks in [peaks_bed_file]. e.g., if [strand] is set to be "minus", 
  # then only reads that are mapped to the minus strand will be compared to the peaks in [peaks_bed_file]
  if(strand == "plus"){
    command <- paste("grep \"+\" ", reads_bed_file, "| awk {'print $1\"\t\"$2-1\"\t\"$2'} >", paste(reads_bed_file, ".strand.temp", sep = ""), sep = "")
  } else if(strand == "minus"){
    command <- paste("grep -v \"+\" ", reads_bed_file, "| awk {'print $1\"\t\"$3\"\t\"$3+1'} >", paste(reads_bed_file, ".strand.temp", sep = ""), sep = "")
  } 
  
  system(command)
  command <- paste("bedtools intersect -a ", paste(reads_bed_file, ".strand.temp", sep = ""), " -b ", peaks_bed_file, " -wa | sort | uniq | wc -l", sep = "")
  overlapped <- as.numeric(system(command, intern = TRUE))
  all <- as.numeric(system(paste("cat ", paste(reads_bed_file, ".strand.temp", sep = ""), " | wc -l ", sep = ""), intern = TRUE))
  ratio <- overlapped/all
  # remove intermediate files
  system(paste("rm ", reads_bed_file, ".strand.temp",sep = ""))
  list(overlap = overlapped, all = all, ratio = ratio)
}
