# awk '{print $3}' ../data/Data/20170120_first/Jump-2hmC-sites_5pct.161116_5hmc_2sites_spikein.umi_encoded_adaptor_removed_no_mismatch.sorted.dedup.bam.minus.sorted.5prime.bed | sort | uniq -c | awk '{print $1"\t"$2}' > ../data/Data/20170120_first/Jump-2hmC-sites_5pct.161116_5hmc_2sites_spikein.umi_encoded_adaptor_removed_no_mismatch.sorted.dedup.bam.minus.sorted.5prime.bed.coverage.ave.perbase.tmp
# Rscript ../lib/pipeline_160912_bioinformatics_preprocessing_using_spike_in_andUMI.R ../data/Data/20170120_first/Jump-2hmC-sites_5pct.161116_5hmc_2sites_spikein.umi_encoded_adaptor_removed_no_mismatch.sorted.dedup.bam.minus.sorted.5prime.bed.coverage.ave.perbase.tmp ../data/Data/20170120_first/Jump-2hmC-sites_5pct.161116_5hmc_2sites_spikein.umi_encoded_adaptor_removed_no_mismatch.sorted.dedup.bam.minus.sorted.5prime.bed.coverage.ave.perbase 200
# rm ../data/Data/20170120_first/Jump-2hmC-sites_5pct.161116_5hmc_2sites_spikein.umi_encoded_adaptor_removed_no_mismatch.sorted.dedup.bam.minus.sorted.5prime.bed.coverage.ave.perbase.tmp
# 
# 
# 
# 
# step_sig: 74335c742f888a091ccf36ebc82912fe
#started at Monday, 06. February 2017 02:32PM
#
#time	proc_cpu	proc_mem	children	children_cpu	children_mem
