# macs2 callpeak -t ../unified_data_repo/20170120_second/323T_hmC_seal_cfDNA.hg19_bowtie1.bam -c ../unified_data_repo/20170120_second/323T_cfDNA_input.hg19_bowtie1.bam -f bam -g hs -n ../unified_data_repo/20170120_second/323T_hmc_seal_cfDNA_vs_323T_cfDNA_input.keep_dup_all -qvalue 0.05 --keep-dup all
# 
# 
# step_sig: e449d90dbcc40889610619d532c4e364
#started at Thursday, 02. March 2017 12:28AM
#
#time	proc_cpu	proc_mem	children	children_cpu	children_mem
