# awk '{print $3}' ../data/Data/20170120_first/Jump-NC-2.160811_5hmc_spikein.umi_encoded_adaptor_removed_no_mismatch.sorted.dedup.bam.plus.sorted.5prime.bed ../data/Data/20170120_first/Jump-NC-2.160811_5hmc_spikein.umi_encoded_adaptor_removed_no_mismatch.sorted.dedup.bam.minus.sorted.5prime.bed | sort | uniq -c | awk '{print $1"\t"$2}' > None ../data/Data/20170120_first/Jump-NC-2.160811_5hmc_spikein.umi_encoded_adaptor_removed_no_mismatch.sorted.dedup.bam.minus.sorted.5prime.bed.coverage.ave.perbase.tmp
# Rscript ../lib/pipeline_160912_bioinformatics_preprocessing_using_spike_in_andUMI.R None ../data/Data/20170120_first/Jump-NC-2.160811_5hmc_spikein.umi_encoded_adaptor_removed_no_mismatch.sorted.dedup.bam.minus.sorted.5prime.bed.coverage.ave.perbase.tmp None ../data/Data/20170120_first/Jump-NC-2.160811_5hmc_spikein.umi_encoded_adaptor_removed_no_mismatch.sorted.dedup.bam.minus.sorted.5prime.bed.coverage.ave.perbase 200
# rm None ../data/Data/20170120_first/Jump-NC-2.160811_5hmc_spikein.umi_encoded_adaptor_removed_no_mismatch.sorted.dedup.bam.minus.sorted.5prime.bed.coverage.ave.perbase.tmp
# 
# 
# 
# 
# step_sig: a0961ea2713e4abe4a051d63a902f64c
#started at Friday, 03. February 2017 03:34PM
#
#time	proc_cpu	proc_mem	children	children_cpu	children_mem
