# awk '{print $3}' ../data/Data/20170120_first/Jump-positive.160811_5hmc_spikein.umi_encoded_adaptor_removed_no_mismatch.sorted.dedup.bam.minus.sorted.5prime.bed | sort | uniq -c | awk '{print $1"\t"$2}' > ../data/Data/20170120_first/Jump-positive.160811_5hmc_spikein.umi_encoded_adaptor_removed_no_mismatch.sorted.dedup.bam.minus.sorted.5prime.bed.coverage.ave.perbase.tmp
# Rscript ../lib/pipeline_160912_bioinformatics_preprocessing_using_spike_in_andUMI.R ../data/Data/20170120_first/Jump-positive.160811_5hmc_spikein.umi_encoded_adaptor_removed_no_mismatch.sorted.dedup.bam.minus.sorted.5prime.bed.coverage.ave.perbase.tmp ../data/Data/20170120_first/Jump-positive.160811_5hmc_spikein.umi_encoded_adaptor_removed_no_mismatch.sorted.dedup.bam.minus.sorted.5prime.bed.coverage.ave.perbase 200
# rm ../data/Data/20170120_first/Jump-positive.160811_5hmc_spikein.umi_encoded_adaptor_removed_no_mismatch.sorted.dedup.bam.minus.sorted.5prime.bed.coverage.ave.perbase.tmp
# 
# 
# 
# 
# step_sig: 684e1937cbc121581f3f0d925d2c1816
#started at Friday, 03. February 2017 03:58PM
#
#time	proc_cpu	proc_mem	children	children_cpu	children_mem
