---
title: "Reads statistics of 161130 paired-end reads data"
output: html_document
---

***

```{r,echo=FALSE}
source("../lib/check_reads_and_mapping_for_single_cell_libraries.R")
```


> <span style="color:red; font-family:arial; font-size:1em;">He-Hu-Lu-2_S2_L001_R1_001_5hmC-jump-seq-single-cell</span>


```{r,echo=FALSE,cache=TRUE}
temp = draw_reads_single_cell("He-Hu-Lu-2_S2_L001_R1_001_5hmC-jump-seq-single-cell","../data/Data/20161130/5hmC_jump-seq_single_cell/")
```


```{r,echo=FALSE}
read_number = c(prettyNum(as.numeric(temp$starting_r1)/4,big.mark = ","),
prettyNum(as.numeric(temp$umi_encoded_adaptor_removed_r1)/4,big.mark = ","),
prettyNum(as.numeric(temp$umi_encoded_adaptor_removed_empty_removed_r1)/4,big.mark = ","))

knitr::kable(data.frame(reads = c("raw","after removed reads without Jump-Barcode","after trimming adaptors at both ends"), read_number))

hist(log(1+as.numeric(temp$single_cell_r1),10), breaks = 100, main = "Distribution of log10(Reads+1) over single cells")
mapped_reads = draw_mapped_dedup_reads_single_cell("He-Hu-Lu-2_S2_L001_R1_001_5hmC-jump-seq-single-cell","../data/Data/20161130/5hmC_jump-seq_single_cell/")
hist(log(mapped_reads+1), breaks = 100, main = "Distribution of log10(mapped_reads+1) over single cells")
```

> <span style="color:red; font-family:arial; font-size:1em;">He-Hu-Lu-2_S2_L002_R1_001_5hmC-jump-seq-single-cell</span>

```{r,echo=FALSE,cache=TRUE}
temp = draw_reads_single_cell("He-Hu-Lu-2_S2_L002_R1_001_5hmC-jump-seq-single-cell","../data/Data/20161130/5hmC_jump-seq_single_cell/")
```


```{r,echo=FALSE}
read_number = c(prettyNum(as.numeric(temp$starting_r1)/4,big.mark = ","),
prettyNum(as.numeric(temp$umi_encoded_adaptor_removed_r1)/4,big.mark = ","),
prettyNum(as.numeric(temp$umi_encoded_adaptor_removed_empty_removed_r1)/4,big.mark = ","))

knitr::kable(data.frame(reads = c("raw","after removed reads without Jump-Barcode","after trimming adaptors at both ends"), read_number))

hist(log(1+as.numeric(temp$single_cell_r1),10), breaks = 100, main = "Distribution of log10(Reads+1) over single cells")
mapped_reads = draw_mapped_dedup_reads_single_cell("He-Hu-Lu-2_S2_L002_R1_001_5hmC-jump-seq-single-cell","../data/Data/20161130/5hmC_jump-seq_single_cell/")
hist(log(mapped_reads+1), breaks = 100, main = "Distribution of log10(mapped_reads+1) over single cells")
```

> <span style="color:red; font-family:arial; font-size:1em;">He-Hu-Lu-2_S2_L003_R1_001_5hmC-jump-seq-single-cell</span>

```{r,echo=FALSE,cache=TRUE}
temp = draw_reads_single_cell("He-Hu-Lu-2_S2_L003_R1_001_5hmC-jump-seq-single-cell","../data/Data/20161130/5hmC_jump-seq_single_cell/")
```


```{r,echo=FALSE}
read_number = c(prettyNum(as.numeric(temp$starting_r1)/4,big.mark = ","),
prettyNum(as.numeric(temp$umi_encoded_adaptor_removed_r1)/4,big.mark = ","),
prettyNum(as.numeric(temp$umi_encoded_adaptor_removed_empty_removed_r1)/4,big.mark = ","))

knitr::kable(data.frame(reads = c("raw","after removed reads without Jump-Barcode","after trimming adaptors at both ends"), read_number))

hist(log(1+as.numeric(temp$single_cell_r1),10), breaks = 100, main = "Distribution of log10(Reads+1) over single cells")
mapped_reads = draw_mapped_dedup_reads_single_cell("He-Hu-Lu-2_S2_L003_R1_001_5hmC-jump-seq-single-cell","../data/Data/20161130/5hmC_jump-seq_single_cell/")
hist(log(mapped_reads+1), breaks = 100, main = "Distribution of log10(mapped_reads+1) over single cells")
```

> > <span style="color:red; font-family:arial; font-size:1em;">He-Hu-Lu-2_S2_L004_R1_001_5hmC-jump-seq-single-cell</span>

```{r,echo=FALSE,cache=TRUE}
temp = draw_reads_single_cell("He-Hu-Lu-2_S2_L004_R1_001_5hmC-jump-seq-single-cell","../data/Data/20161130/5hmC_jump-seq_single_cell/")
```


```{r,echo=FALSE}
read_number = c(prettyNum(as.numeric(temp$starting_r1)/4,big.mark = ","),
prettyNum(as.numeric(temp$umi_encoded_adaptor_removed_r1)/4,big.mark = ","),
prettyNum(as.numeric(temp$umi_encoded_adaptor_removed_empty_removed_r1)/4,big.mark = ","))

knitr::kable(data.frame(reads = c("raw","after removed reads without Jump-Barcode","after trimming adaptors at both ends"), read_number))

hist(log(1+as.numeric(temp$single_cell_r1),10), breaks = 100, main = "Distribution of log10(Reads+1) over single cells")
mapped_reads = draw_mapped_dedup_reads_single_cell("He-Hu-Lu-2_S2_L004_R1_001_5hmC-jump-seq-single-cell","../data/Data/20161130/5hmC_jump-seq_single_cell/")
hist(log(mapped_reads+1), breaks = 100, main = "Distribution of log10(mapped_reads+1) over single cells")
```


> <span style="color:green; font-family:arial; font-size:1em;">Example 1 reads after preprocessing before mapping</span>

```
# highly abundant across single cell libraries.
Read1(after preprocessing)

@NB501189:34:HWGLNBGXY:4:11401:9355:6051_GCCCTGTT 1:N:0:GCGATCTA
AATGAATGAATTTTCTGAATCTGCACAGGTCCTTACTACTCTAATTCAAAATGGGCCTTA
+
<AEEEEEEEEEEEAEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

Read2(after preprocessing)

@NB501189:34:HWGLNBGXY:4:11401:9355:6051_GCCCTGTT 2:N:0:GCGATCTA
ATTTTACCTTCCTGCTCGAATAGCGTAGCAAAGTTGGACAAACCATAA
+
6AEEEAEAEEE6EEEEEEEAE<E<<E/AE<//EAE/AAEEEEEAEEAE

Read1 (raw)

@NB501189:34:HWGLNBGXY:4:11401:9355:6051 1:N:0:GCGATCTA
GCCCTGTTTGACTCGAATGAATGAATTTTCTGAATCTGCACAGGTCCTTACTACTCTAATTCAAAATGGGCCTTA
+
AAAAAEEEEE6AAAE<AEEEEEEEEEEEAEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

Read2 (raw)

@NB501189:34:HWGLNBGXY:4:11401:9355:6051 2:N:0:GCGATCTA
GTAGTCACAGATGTGTATAAGAGACAGATTTTACCTTCCTGCTCGAATAGCGTAGCAAAGTTGGACAAACCATAA
+
AAAAAEAEAEAEAEAEEEEEEEEEA<E6AEEEAEAEEE6EEEEEEEAE<E<<E/AE<//EAE/AAEEEEEAEEAE
```

> <span style="color:green; font-family:arial; font-size:1em;">Example 2 reads after/before preprocessing before mapping</span>

```
Read1 (after preprocessing)

@NB501189:34:HWGLNBGXY:4:11401:12416:7662_TTAGGGGC 1:N:0:GCGATCTA
GACGACGAGTCAAGGACCAC
+
AEEEEEEEEEEEEEEEEEEE

Read2 (after preprocessing)

@NB501189:34:HWGLNBGXY:4:11401:12416:7662_TTAGGGGC 2:N:0:GCGATCTA
GTGGTCCTTGACTCGTCGTC
+
/6/EEEEEE/E<EAEEEEEA

Read1 (raw)

@NB501189:34:HWGLNBGXY:4:11401:12416:7662 1:N:0:GCGATCTA
TTAGGGGCTGACTCGGACGACGAGTCAAGGACCACCTGTCTCTTATACACATCTGTGACTACCCGAGCCCACGAG
+
AAAAAEEEEE6A<AEAEEEEEEEEEEEEEEEEEEEE/EEEEEEEEEEEEEEEEEEEE/EEEE/AE<EAAEEEEE/

Read2 (raw)

@NB501189:34:HWGLNBGXY:4:11401:12416:7662 1:N:0:GCGATCTA
TTAGGGGCTGACTCGGACGACGAGTCAAGGACCACCTGTCTCTTATACACATCTGTGACTACCCGAGCCCACGAG
+
AAAAAEEEEE6A<AEAEEEEEEEEEEEEEEEEEEEE/EEEEEEEEEEEEEEEEEEEE/EEEE/AE<EAAEEEEE/
```
> <span style="color:green; font-family:arial; font-size:1em;">Example 3 reads after/before preprocessing before mapping</span>

```
Read1 (after preprocessing)

@NB501189:34:HWGLNBGXY:4:11401:25578:5358_GTTGTCCT 1:N:0:GCGATCTA
TTCGATCGAGTCAGCCCCTAA
+
EEEEEEEEEEEEEEEEEEEEE

Read2 (after preprocessing)

@NB501189:34:HWGLNBGXY:4:11401:25578:5358_GTTGTCCT 2:N:0:GCGATCTA
TTAGGGGCTGACTCGATCGAA
+
EE/EEEEEEEEEE/EEEEEEE


Read1 (raw)

@NB501189:34:HWGLNBGXY:4:11401:25578:5358 1:N:0:GCGATCTA
GTTGTCCTTGACTCGTTCGATCGAGTCAGCCCCTAACTGTCTCTTATACACATCTGTGACTACCCGAGCCCACGA
+
AAAAAEEEEE6</AEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

Read 2 (raw)

@NB501189:34:HWGLNBGXY:4:11401:25578:5358 2:N:0:GCGATCTA
GTAGTCACAGATGTGTATAAGAGACAGTTAGGGGCTGACTCGATCGAACGAGTCAAGGACAACCTGTCTCTTATA
+
AAAAAEEEEAEEAEEEEEEEEEAEEAEEE/EEEEEEEEEE/EEEEEEEEAEAAEEAEEAEEEEEE6EEEEEEEEE
```